### ISSUE TITLE
Why is properties set to 0.4.0?

### ISSUE THREAD

**Issue by banesullivan** [gmggroup/omf-python#30]
https://github.com/gmggroup/omf/blob/b2748c91d599b5bce1f382829a76a66b10eb0668/setup.py#L29

Can we upgrade this dependency/figure out why it's having issues on Python 2.7?

```txt
Traceback (most recent call last):
  File "tests/__main__.py", line 49, in <module>
    test(close=close)
  File "tests/__main__.py", line 31, in test
    in module_strings]
  File "/opt/python/2.7.14/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/travis/build/OpenGeoVis/PVGeo/tests/model_build_test.py", line 9, in <module>
    from PVGeo.model_build import *
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/PVGeo-1.1.42-py2.7.egg/PVGeo/__init__.py", line 30, in <module>
    import omf
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/omf/__init__.py", line 8, in <module>
    from .data import (ColorArray, ColorData,
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/omf/data.py", line 14, in <module>
    class ScalarArray(UidModel):
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/omf/data.py", line 19, in ScalarArray
    deserializer=array_deserializer(('*',))
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/properties/basic.py", line 82, in __call__
    instance = super(ArgumentWrangler, cls).__call__(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/properties/basic.py", line 119, in __init__
    'Cannot set attribute: "{}".'.format(key)
AttributeError: Cannot set attribute: "deserializer".
```

**Comment by fwkoch** [comment]
Thanks @banesullivan - I just saw this issue a few days ago, the fix in properties is here: https://github.com/seequent/properties/pull/265

Once that is landed, I'll update `omf` to latest properties - no reason it's on 0.4.0 other than lack of update.

**Comment by fwkoch** [comment]
@banesullivan - this should be fixed with the latest release. https://github.com/gmggroup/omf/releases/tag/v1.0.0
